// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9GFXYejsr4kPn507CmrucPoU8xam11Dc',
    appId: '1:586215331549:web:41b4a6f26287e72333ed34',
    messagingSenderId: '586215331549',
    projectId: 'assignment-app-35607',
    authDomain: 'assignment-app-35607.firebaseapp.com',
    storageBucket: 'assignment-app-35607.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMF3G09pXqXat8WXTlXC6Da2WQdahgn2c',
    appId: '1:586215331549:android:02ab34abada8134133ed34',
    messagingSenderId: '586215331549',
    projectId: 'assignment-app-35607',
    storageBucket: 'assignment-app-35607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArc2m9ws3264LE-Z9zKyY6pessSygPo_o',
    appId: '1:586215331549:ios:92e5ed317f01eaa433ed34',
    messagingSenderId: '586215331549',
    projectId: 'assignment-app-35607',
    storageBucket: 'assignment-app-35607.firebasestorage.app',
    iosBundleId: 'com.example.assignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArc2m9ws3264LE-Z9zKyY6pessSygPo_o',
    appId: '1:586215331549:ios:92e5ed317f01eaa433ed34',
    messagingSenderId: '586215331549',
    projectId: 'assignment-app-35607',
    storageBucket: 'assignment-app-35607.firebasestorage.app',
    iosBundleId: 'com.example.assignmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9GFXYejsr4kPn507CmrucPoU8xam11Dc',
    appId: '1:586215331549:web:6243bcb80dcbb94033ed34',
    messagingSenderId: '586215331549',
    projectId: 'assignment-app-35607',
    authDomain: 'assignment-app-35607.firebaseapp.com',
    storageBucket: 'assignment-app-35607.firebasestorage.app',
  );
}
